### ISSUE TITLE
This project needs a maintainer

### ISSUE THREAD

**Issue by bashu** [gadventures/django-fsm-admin#84]
Hi,

This repository seems to lack maintenance, I propose myself as a new maintainer.

Could you give me the right to push in your repository or just transfer it on my account in github?

Thank you!

**Comment by bashu** [comment]
We still use it some legacy projects and I am willing to keep it maintained. If you are not sure about me, for example I maintain (or helping to maintain):

https://github.com/shanx/django-maintenancemode

https://github.com/adamcharnock/django-tz-detect

Also I adopted few Django projects and still continue maintaining them, biggest example:

https://github.com/bashu/django-easy-maps

**Comment by bashu** [comment]
cc @Nagyman

**Comment by Nagyman** [comment]
@bashu I no longer work for G Adventures, but I agree this could use one or more maintainers. I wouldn't mind resuming maintenance since I'm still actively using Django and this is rather handy. The best bet is to fork the repo and continue work there.

With respect to the release on PyPi (https://pypi.org/project/django-fsm-admin/), I no longer have access to that either, but perhaps someone still at G Adventures can transfer that maintainer-ship, in absence of any interest on their end. TBD if the credentials can be recovered though. Let me contact a remaining developer.

**Comment by ticosax** [comment]
Hi @marz619 
Have you considered moving the project to jazzband ?
https://jazzband.co/

**Comment by marz619** [comment]
@bashu  we've gotten internal signoff to add maintainers to this project.

For now we'll be adding @Nagyman and we're open to adding additional maintainers in the future as needed.

**Comment by fabianbuechler** [comment]
Great to hear the project has a new maintainer!
Are you planning to do a release with the changes already in `master`?

**Comment by bashu** [comment]
anyone?

**Comment by marz619** [comment]
> anyone?

Hey @bashu apologies for the radio silence. We had a discussion internally and agreed that we need to open up the maintenance of this project. We will send you an invite to become a maintainer on this project in order to get things moving again.

Our next steps will be to explore the possible transfer of ownership of the project as well, but as yet do not necessarily have the concrete steps to make that change, but are open to discuss.

We will also need to provide you with maintainer privileges on Pypi as well so that releases can be pushed, so if you could send me your pypi user name to `aesmailjee [at] gadventures [dot] com` and I'll send you an invite there as well.

Again, apologies for the delay and look forward to working with you more actively going forward.

**Comment by bashu** [comment]
to @marz619 I am going to start tomorrow and thank you for invitation
